# Generated by Django 5.2.17 on 2026-08-11 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Actor/crew member's real name", max_length=200
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("title", models.CharField(db_index=True, max_length=200)),
                (
                    "original_title",
                    models.CharField(
                        blank=True,
                        help_text="Original title if different from translated title",
                        max_length=200,
                    ),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tmdb_vote_average",
                    models.FloatField(
                        blank=True,
                        help_text="TMDB rating out of 10",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("synopsis", models.TextField(blank=True)),
                (
                    "backdrop_path",
                    models.CharField(
                        blank=True,
                        help_text="TMDB relative image path (e.g. '/8kSerJrhrJWKLk1LViesGcnrUPE.jpg') -- not a full URL, combine with TMDB's image base URL + a size via backdrop_url()",
                        max_length=255,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "budget_usd",
                    models.BigIntegerField(
                        blank=True, help_text="Budget in USD", null=True
                    ),
                ),
                (
                    "revenue_usd",
                    models.BigIntegerField(
                        blank=True, help_text="Revenue in USD", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="movies.genre"
                    ),
                ),
            ],
            options={
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="CrewCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("job", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_credits",
                        to="movies.movie",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="movies.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CastCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(blank=True, max_length=200)),
                ("billing_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cast_credits",
                        to="movies.movie",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="movies.person",
                    ),
                ),
            ],
            options={
                "ordering": ["billing_order"],
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="cast",
            field=models.ManyToManyField(
                related_name="acting_credits",
                through="movies.CastCredit",
                to="movies.person",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="crew",
            field=models.ManyToManyField(
                related_name="crew_credits",
                through="movies.CrewCredit",
                to="movies.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="crewcredit",
            constraint=models.UniqueConstraint(
                fields=("movie", "person", "job"), name="unique_crew_credit"
            ),
        ),
        migrations.AddConstraint(
            model_name="castcredit",
            constraint=models.UniqueConstraint(
                fields=("movie", "person", "character_name"), name="unique_cast_credit"
            ),
        ),
    ]
