# Generated by Django 5.2.17 on 2026-08-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="person",
            name="birth_date",
        ),
    ]
