# Generated by Django 5.2.17 on 2026-08-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_remove_person_bio_remove_person_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="original_title",
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
