# Generated by Django 5.2.17 on 2026-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_remove_movie_original_title_alter_movie_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="castcredit",
            name="character_name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(
                help_text="Actor/crew member's real name", max_length=300
            ),
        ),
    ]
